export const STAT_ICONS = [
  "groups",
  "event",
  "library_books",
  "volunteer_activism",
  "school",
  "map",
  "diversity_3",
  "favorite",
  "handshake",
  "menu_book",
  "workspace_premium",
  "campaign",
  "public",
  "home",
  "star",
  "celebration",
  "health_and_safety",
  "psychology",
  "emoji_events",
  "trending_up",
  "support",
  "forest",
  "water_drop",
  "local_hospital",
  "child_care",
  "woman",
  "man",
  "family_restroom",
  "apartment",
  "account_balance",
] as const;

export type StatIcon = (typeof STAT_ICONS)[number];
